services:
  mongo:
    image: mongo:latest
    restart: always
    ports: [ 27019:27017 ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mgadmin
      MONGO_INITDB_ROOT_PASSWORD: mgpasswd
      MONGO_INITDB_DATABASE: owa-db
    volumes:  [ ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js ]

  mongo-express:
    # interface credentials: admin / pass
    image: mongo-express 
    restart: always
    ports: [ 8081:8081 ]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mgadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mgpasswd
      ME_CONFIG_MONGODB_URL: mongodb://mgadmin:mgpasswd@mongo:27017
