version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: owa-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mgadmin
      MONGO_INITDB_ROOT_PASSWORD: mgpasswd
      MONGO_INITDB_DATABASE: owa-db
    networks:
      - owa-network
    ports:
      - "27019:27017"  
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo
    networks:
      - owa-network
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: ["mongosh", "--host", "owa-mongo", "--file", "/docker-entrypoint-initdb.d/init-mongo.js"]
    restart: "on-failure"

networks:
  owa-network:
    driver: bridge

volumes:
  mongo-data:
